### ISSUE TITLE
Seems None is Active

### ISSUE THREAD

**Issue by sideffect0** [OpenGenus/Find.the.Lost#3]
Seems none is active, is what was the project about to start??

**Comment by JessiPal** [comment]
Our group is very much active but things are moving slow. In a month, all things will move systematically. Our project has started and we are expanding our developer base and reaching out to other parts of the world.

**Comment by MichalPaszkiewicz** [comment]
There doesn't seem to be much progress here?

**Comment by JessiPal** [comment]
Actually, we are planning the workflow. Good to see your interest in our social pursuit.

**Comment by AdiChat** [comment]
Hello @MichalPaszkiewicz  @JessiPal
I have been thinking over building an application around the twitter api to track emotionally lost people and notify nearby people so that some company/ guidance may be provided. I have been planning out the workflow for the application. I believe it would be a great tool for social recovery and may save lots of depressed hearts. 
If we all join together and work, it may be up and running in a couple of months. 
I believe it will be a great opportunity to collaborate and a great product for social use. :)
Please share your thoughts and ideas upon this.
I am closely attached to this thought and hence, want to start as soon as possible.

**Comment by JessiPal** [comment]
Sounds good @AdiChat 
This would be a great start. Let us work out the workflow and find out who are willing to give back to the society and then, we will be up and running.

**Comment by MichalPaszkiewicz** [comment]
^^ Sounds interesting! 

Please keep us updated

**Comment by sideffect0** [comment]
If workflow is set, am ready :+1:  @AdiChat @MichalPaszkiewicz

**Comment by JessiPal** [comment]
Join the discussion of work flow at OpenGenus/ProjectBot#2 if you are aiming to contribute in near future. 😄 
@AdiChat @BastiaanDeHart @brunocasanova @catom @datudou @FannyVieira @hashimshafiq @jaimejhonle @KarimGabr @kilfu0701 @LandyGuo @MauricioTorre @MichalPaszkiewicz @pablofernandezcom @recepcoban @sideffect0 @tacheshun @tomatohunter @wulfgarpro
